# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: MIT

name: flutterbrolibs
description: This package contains all the packages I have created for Flutter applications.
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - bro_abstract_logger
  - bro_abstract_manager
  - bro_config_manager
  - bro_file_utility
  - bro_global_manager
  - bro_list_utility
  - bro_types_utility
  - bro_yaml_utility

dev_dependencies:
  mono_repo: ^6.6.2
  flutter_lints: ^5.0.0
