# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: MIT

name: bro_list_utility
description: This package contains utility classes for lists.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  bro_abstract_logger:
    path: ../bro_abstract_logger

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
