name: bro_config_manager
description: "A new Flutter package project."
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  flutter_dotenv: ^5.2.1

  bro_abstract_logger:
    path: ../bro_abstract_logger

  bro_abstract_manager:
    path: ../bro_abstract_manager

  bro_global_manager:
    path: ../bro_global_manager

  bro_json_utility:
    path: ../bro_json_utility

  bro_list_utility:
    path: ../bro_list_utility

  bro_types_utility:
    path: ../bro_types_utility

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
