# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: MIT

name: bro_auth_manager
version: 1.0.0

description: The package contains abstract classes for authentication management.
repository: https://github.com/borlnov/flutterbrolibs
issue_tracker: https://github.com/borlnov/flutterbrolibs/issues
topics:
  - manager
  - authentication
  - brolibs
  - shared

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
