# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: MIT

name: bro_global_manager
description: This contains the abstract global manager for the application.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bro_abstract_manager:
    path: ../bro_abstract_manager

  bro_abstract_logger:
    path: ../bro_abstract_logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  equatable: ^2.0.7
