# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Flutter Unit Tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: for i in $(git ls-files --recurse-submodules "*/pubspec.yaml"); do
          (cd "${i%pubspec.yaml}" && [ -d "test" ] && flutter test -r github --flavor test); done
