# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <borlnov.obsessio@gmail.com>

# SPDX-License-Identifier: MIT

# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags:
      - '[A-z]+-v[0-9]+.[0-9]+.[0-9]+*'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    if: ${{ github.repository_owner == 'borlnov' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions:
      id-token: write # Required for authentication using OIDC
      pull-requests: write # Required for writing the pull request note
    with:
      # Protected github deployment environment, requires approval to publish.
      environment: pub.dev
      use-flutter: true
